### ISSUE TITLE
error genorating qr codes for certain users

### ISSUE THREAD

**Issue by mjrb** [HackRU/OneAppFlutter#33]
```
 ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4132): The following assertion was thrown during paint():
I/flutter ( 4132): Failed assertion: boolean expression must not be null
I/flutter ( 4132): 
I/flutter ( 4132): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4132): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4132): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4132):   https://github.com/flutter/flutter/issues/new?template=BUG.md
#0      QrPainter.paint (package:qr_flutter/src/qr_painter.dart:71:17)
I/flutter ( 4132): #1      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:521:13)
I/flutter ( 4132): #2      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:559:7)
I/flutter ( 4132): #3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #5      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4132): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #11     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:222:15)
I/flutter ( 4132): #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #14     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4132): #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #20     _RenderListBody&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 4132): #21     RenderListBody.paint (package:flutter/src/rendering/list_body.dart:264:5)
I/flutter ( 4132): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #24     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4132): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #27     _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:522:17)
I/flutter ( 4132): #28     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 4132): #29     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:394:7)
I/flutter ( 4132): #30     _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:526:17)
I/flutter ( 4132): #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #32     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4132): #33     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4132): #34     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4132): #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4132): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #43     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2629:11)
I/flutter ( 4132): #44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #54     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4132): #55     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4132): #56     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4132): #57     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4132): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #59     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:562:11)
I/flutter ( 4132): #60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #64     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4132): #65     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4132): #66     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4132): #67     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4132): #68     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 4132): #69     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
I/flutter ( 4132): #70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #79     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #82     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:504:11)
I/flutter ( 4132): #83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #84     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #85     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #86     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:562:11)
I/flutter ( 4132): #87     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #88     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #90     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 4132): #91     RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:1830:17)
I/flutter ( 4132): #92     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #94     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #97     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4132): #98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #100    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4132): #101    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #102    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #103    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 4132): #104    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #105    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #106    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #107    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #108    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #109    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #110    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #111    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4132): #112    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4132): #113    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 4132): #114    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 4132): #115    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #116    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #117    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #118    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #119    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 4132): #120    PaintingContext.pushOpacity (package:flutter/src/rendering/object.dart:492:5)
I/flutter ( 4132): #121    RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:914:15)
I/flutter ( 4132): #122    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #123    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 4132): #124    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 4132): #125    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter ( 4132): #126    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 4132): #127    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 4132): #128    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:853:29)
I/flutter ( 4132): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:331:19)
I/flutter ( 4132): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 4132): #131    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 4132): #132    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 4132): #133    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 4132): #134    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 4132): #138    _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 4132): #139    _drawFrame (dart:ui/hooks.dart:168:3)
```

**Comment by dhruvilp** [comment]
looking into it. It's an issue with the library so fixing it

**Comment by dhruvilp** [comment]
has been fixed
